sky:
  datasource:
    driver-class-name:
    host:
    port:
    database:
    username:
    password:
  alioss:
    endpoint:
    access-key-id:
    access-key-secret:
    bucket-name:
  redis:
    host:
    port:
    password:
    database:
  wechat:
    appid:
    secret: